

SELECT * FROM BIGMAKI;

-- Alteração de qiantidades vendida

UPDATE BIGMAKI SET  QUANTIDADE = 36 WHERE CODIGO = '157';
UPDATE BIGMAKI SET  QUANTIDADE = 36 WHERE CODIGO = '162';
UPDATE BIGMAKI SET  QUANTIDADE = 36 WHERE CODIGO = '165';
UPDATE BIGMAKI SET  QUANTIDADE = 36 WHERE CODIGO = '178';

-- alterar Unidade
UPDATE BIGMAKI SET UNIDADES = 'barra' WHERE CODIGO = '158';
UPDATE BIGMAKI SET UNIDADES = 'copacabana' WHERE CODIGO = '158';

UPDATE BIGMAKI SET UNIDADES = 'niteroi' WHERE CODIGO = '160';
UPDATE BIGMAKI SET UNIDADES = 'barra' WHERE CODIGO = '160';

-- Alterar valor da venda

UPDATE BIGMAKI SET [VALOR DE VENDA] = 19.50 WHERE PRODUTO = 'Bigmaki hot croc calmon';
UPDATE BIGMAKI SET [VALOR DE VENDA] = 21.80 WHERE PRODUTO = 'Bigmaki philadelphia salmon';
SELECT PRODUTO, [VALOR DE VENDA] FROM BIGMAKI WHERE PRODUTO = 'Bigmaki hot croc calmon';
SELECT PRODUTO, [VALOR DE VENDA] FROM BIGMAKI WHERE PRODUTO = 'Bigmaki philadelphia salmon';

-- Alterar total da vendaa
SELECT PRODUTO, [VALOR DE VENDA], QUANTIDADE, [TOTAL DE VENDAS] FROM BIGMAKI WHERE PRODUTO = 'Bigmaki philadelphia salmon';
SELECT PRODUTO, [VALOR DE VENDA], QUANTIDADE, [TOTAL DE VENDAS] FROM BIGMAKI WHERE PRODUTO = 'Bigmaki hot croc calmon';
UPDATE BIGMAKI SET [TOTAL DE VENDAS] = 975.00 WHERE PRODUTO = 'Bigmaki hot croc calmon';
UPDATE BIGMAKI SET [TOTAL DE VENDAS] = 1090.00 WHERE PRODUTO = 'Bigmaki philadelphia salmon';


-- Alterar a linha inteira
SELECT * FROM P_COMECAR;

UPDATE P_COMECAR SET PRODUTO = 'CEVICHE VIEIRA',
UNIDADES = 'copacabana',
[VALOR DE VENDA] = 13.50,
QUANTIDADE = 23,
[TOTAL DE VENDAS] = 310.50
WHERE CODIGO = 192;

SELECT * FROM P_COMECAR WHERE CODIGO = 192;


SELECT * FROM SOBREMESA;
UPDATE SOBREMESA SET PRODUTO = 'BRIGADEIRO DE COLHER',
UNIDADES = 'niteroi',
[VALOR DE VENDA] = 15.00,
QUANTIDADE = 28,
[TOTAL DE VENDAS] = 420.00
WHERE CODIGO = 376;

SELECT * FROM SOBREMESA WHERE CODIGO = 376;

-- Deletar Linha e tabela
SELECT * FROM YAKISOBA;

DELETE FROM YAKISOBA WHERE CODIGO = 156;
DELETE FROM YAKISOBA;








